extends: default

rules:
  line-length:
    max: 150
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "yes"]
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true

ignore:
  - .git/
