apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap-kustomization.yaml
  - secrets-kustomization.yaml
  - litellm-db-kustomization.yaml
  - inference-kustomization.yaml
  - mcp-template-kustomization.yaml
  - litellm-kustomization.yaml
  - litellm-bootstrap-kustomization.yaml
  - networking-kustomization.yaml
  - observability-kustomization.yaml
