apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../flux/bootstrap-kustomization.yaml
  - ../../flux/secrets-kustomization.yaml
  - ../../flux/litellm-db-kustomization.yaml
  - ../../flux/inference-kustomization.yaml
  - ../../flux/mcp-template-kustomization.yaml
  - ../../flux/litellm-staging-kustomization.yaml
  - ../../flux/litellm-bootstrap-kustomization.yaml
  - ../../flux/networking-kustomization.yaml
  - ../../flux/observability-kustomization.yaml
